In [21]:
import sys
sys.path.append('..')

import warnings
warnings.filterwarnings('ignore')

## Occupancy Data Preparing

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
path_to_file = '../datasets/classification/occupancy_detection_preprocessed.csv'
classification_df = pd.read_csv(path_to_file, index_col=0)

classification_df = classification_df.drop(['date'], axis=1)

X = classification_df.iloc[:, :-1].values
y = classification_df.iloc[:, 5].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, 
                                                    stratify=y)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
y_train, y_test = np.array(y_train), np.array(y_test)

In [6]:
y_train

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [7]:
X_train

array([[-0.48901103, -1.80559367, -0.62177187, -0.84445619, -1.92079098],
       [-1.28710967,  2.25914444, -0.62177187, -0.61030445,  1.6351377 ],
       [-0.01395231, -0.45391758, -0.62177187, -0.52452075, -0.45952336],
       ...,
       [ 1.13568978, -0.29722092,  1.52501494,  1.10860672,  0.10135604],
       [ 0.09056061,  1.69463468, -0.62177187,  1.86933012,  1.74174245],
       [ 0.25683116,  0.94781439, -0.62177187, -0.51319083,  1.05826514]])

## Interstate Data Preparing

In [4]:
path_to_file = '../datasets/regression/metro_interstate_traffic_volume_preprocessed.csv'
regression_df = pd.read_csv(path_to_file)

regression_df = regression_df.drop(['Unnamed: 0', 'date_time'], axis=1)

X = regression_df.iloc[:, [0, 1, 2, 3] + list(range(5, 65))]
y = regression_df.iloc[:, 4]

reg_X_train, reg_X_test, reg_y_train, reg_y_test = train_test_split(X, y, test_size=0.2)


scaler = StandardScaler()
scaler.fit(reg_X_train)


reg_X_train = scaler.transform(reg_X_train)
reg_X_test = scaler.transform(reg_X_test)

reg_y_train, reg_y_test = np.array(reg_y_train), np.array(reg_y_test)

In [5]:
reg_X_train

array([[-0.35251634, -0.12807276, -0.02890726, ..., -0.03301991,
        -0.02695574, -0.01836367],
       [-0.20876858, -0.12807276, -0.02890726, ..., -0.03301991,
        -0.02695574, -0.01836367],
       [ 1.06464089, -0.12807276, -0.02890726, ..., -0.03301991,
        -0.02695574, -0.01836367],
       ...,
       [ 0.47760815,  0.75038196, -0.02890726, ..., -0.03301991,
        -0.02695574, -0.01836367],
       [ 1.1903261 , -0.12807276, -0.02890726, ..., -0.03301991,
        -0.02695574, -0.01836367],
       [ 0.65055703, -0.12807276, -0.02890726, ..., -0.03301991,
        -0.02695574, -0.01836367]])

In [6]:
reg_y_train

array([2044, 4749, 4126, ..., 6529, 2611, 4813], dtype=int64)

## Iris Data Preparing

In [107]:
path_to_iris = "../datasets/mlp_test/iris.csv"
iris_df = pd.read_csv(path_to_iris, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'])

In [108]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [109]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [110]:
iris_df['class'].value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: class, dtype: int64

In [111]:
iris_df = pd.get_dummies(iris_df, columns=['class'])

In [112]:
iris_df = iris_df.sample(frac=1).set_index(np.arange(150))

In [113]:
iris_X = iris_df.iloc[:, :4]
iris_y = iris_df.iloc[:, [-1, -2, -3]]

In [114]:
iris_X_train, iris_X_test, iris_y_train, iris_y_test = train_test_split(iris_X, iris_y, 
                                                                        test_size=0.20)

scaler = StandardScaler()
scaler.fit(iris_X_train)
iris_X_train = scaler.transform(iris_X_train)
iris_X_test = scaler.transform(iris_X_test)

In [115]:
iris_y_train = iris_y_train.to_numpy()
iris_y_test = iris_y_test.to_numpy()

## Titanic Data Preparing

In [181]:
path_to_titanic = '../datasets/mlp_test/titanic.csv'
titanic_df = pd.read_csv(path_to_titanic)

In [182]:
titanic_df.head()

PassengerID                                           Name PClass    Age  \
0            1                   Allen, Miss Elisabeth Walton    1st  29.00   
1            2                    Allison, Miss Helen Loraine    1st   2.00   
2            3            Allison, Mr Hudson Joshua Creighton    1st  30.00   
3            4  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00   
4            5                  Allison, Master Hudson Trevor    1st   0.92   

      Sex  Survived  SexCode  
0  female         1        1  
1  female         0        1  
2    male         0        0  
3  female         0        1  
4    male         1        0

In [183]:
titanic_df = titanic_df.drop(labels=['PassengerID', 'Name', 'Sex'], axis=1)
titanic_df

PClass    Age  Survived  SexCode
0       1st  29.00         1        1
1       1st   2.00         0        1
2       1st  30.00         0        0
3       1st  25.00         0        1
4       1st   0.92         1        0
...     ...    ...       ...      ...
1308    3rd  27.00         0        0
1309    3rd  26.00         0        0
1310    3rd  22.00         0        0
1311    3rd  24.00         0        0
1312    3rd  29.00         0        0

[1313 rows x 4 columns]

In [184]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   PClass    1313 non-null   object 
 1   Age       756 non-null    float64
 2   Survived  1313 non-null   int64  
 3   SexCode   1313 non-null   int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 41.2+ KB


In [185]:
titanic_df = titanic_df.fillna(titanic_df['Age'].mean())
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   PClass    1313 non-null   object 
 1   Age       1313 non-null   float64
 2   Survived  1313 non-null   int64  
 3   SexCode   1313 non-null   int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 41.2+ KB


In [186]:
titanic_df['Survived'].value_counts()

0    863
1    450
Name: Survived, dtype: int64

In [188]:
titanic_df.iloc[456]

PClass              *
Age         30.397989
Survived            0
SexCode             0
Name: 456, dtype: object

In [189]:
titanic_df = titanic_df.drop(titanic_df[titanic_df['PClass'] == '*'].index)

In [190]:
mapping = {'1st': 1,
           '2nd': 2,
           '3rd': 3 }

titanic_df['PClass'] = titanic_df['PClass'].map(mapping)
titanic_df

PClass    Age  Survived  SexCode
0          1  29.00         1        1
1          1   2.00         0        1
2          1  30.00         0        0
3          1  25.00         0        1
4          1   0.92         1        0
...      ...    ...       ...      ...
1308       3  27.00         0        0
1309       3  26.00         0        0
1310       3  22.00         0        0
1311       3  24.00         0        0
1312       3  29.00         0        0

[1312 rows x 4 columns]

In [191]:
titanic_X = titanic_df.iloc[:, [0, 1, 3]]
titanic_y = titanic_df.iloc[:, 2]

In [192]:
titanic_X_train, titanic_X_test, titanic_y_train, titanic_y_test = \
    train_test_split(titanic_X, titanic_y, test_size=0.2, stratify=titanic_y)

scaler = StandardScaler()
scaler.fit(titanic_X_train)
titanic_X_train = scaler.transform(titanic_X_train)
titanic_X_test = scaler.transform(titanic_X_test)

In [193]:
titanic_y_train = titanic_y_train.to_numpy()
titanic_y_test = titanic_y_test.to_numpy()

In [194]:
titanic_X_train[:10]

array([[ 0.86203092,  0.00174785, -0.7474573 ],
       [-1.51450111,  1.15063077,  1.33786906],
       [-1.51450111,  1.51529732, -0.7474573 ],
       [-0.32623509,  0.00174785,  1.33786906],
       [ 0.86203092, -0.85503524,  1.33786906],
       [-0.32623509,  0.9682975 , -0.7474573 ],
       [ 0.86203092,  0.00174785, -0.7474573 ],
       [ 0.86203092,  0.42129768,  1.33786906],
       [-0.32623509, -1.40203505,  1.33786906],
       [ 0.86203092,  0.00174785, -0.7474573 ]])

## MLP Testing

In [7]:
from my_implementations.multilayer_perceptron.mlp import MultilayerPerceptron
from my_implementations.multilayer_perceptron.activation_functions import ActivationFunction

### My classification dataset

In [15]:
model = MultilayerPerceptron(0.1, 500, 10, [
    (3, ActivationFunction.rectified_linear_unit),
    (4, ActivationFunction.rectified_linear_unit),
    (1, ActivationFunction.sigmoid)
])

In [16]:
%%time
model.fit(X_train, y_train)

Wall time: 12.9 s


In [19]:
predictions = model.predict(X_test)

In [23]:
preds = predictions.reshape((predictions.shape[0],))

In [26]:
preds[preds >= 0.5] = 1
preds[preds < 0.5] = 0

In [31]:
print(f"Accuracy: {100 * sum(preds == y_test) / len(y_test):.2f}%")

Accuracy: 98.88%


## My regression dataset

In [26]:
reg_model = MultilayerPerceptron(0.1, 500, 10, [
    (4, ActivationFunction.rectified_linear_unit),
    (8, ActivationFunction.rectified_linear_unit),
    (8, ActivationFunction.rectified_linear_unit),
    (1, ActivationFunction.rectified_linear_unit)
])

In [27]:
%%time
reg_model.fit(reg_X_train, reg_y_train)

Wall time: 1min 7s


In [28]:
predictions = reg_model.predict(reg_X_test)

In [29]:
preds = predictions.reshape((predictions.shape[0],))

In [30]:
np.sum(np.sqrt((reg_y_test - preds)**2)) / len(reg_y_test)

3297.9306088580024

Перцептрон основан на кросс-энтропийной функции потерь, которая ориентирована на классификацию. Ошибка большая на других моделях в том числе.

### Iris dataset

In [161]:
iris_model = MultilayerPerceptron(0.1, 500, 10, [
    (3, ActivationFunction.rectified_linear_unit),
    (4, ActivationFunction.rectified_linear_unit),
    (3, ActivationFunction.sigmoid)
])

In [162]:
%%time
iris_model.fit(iris_X_train, iris_y_train)

Wall time: 581 ms


In [163]:
iris_predictions = iris_model.predict(iris_X_test)

In [164]:
for row_idx in range(iris_predictions.shape[0]):
    iris_predictions[row_idx, iris_predictions[row_idx] == iris_predictions[row_idx].max()] = 1
    iris_predictions[row_idx, iris_predictions[row_idx] != iris_predictions[row_idx].max()] = 0

In [165]:
check_predictions = [all(pred_row == test_row) for pred_row, test_row in zip(iris_predictions, iris_y_test)]

In [166]:
print(f"Accuracy: {100 * sum(check_predictions) / len(iris_y_test):.2f}%")

Accuracy: 96.67%


### Titanic dataset

In [271]:
titanic_model = MultilayerPerceptron(0.01, 500, 10, [
    (3, ActivationFunction.rectified_linear_unit),
    (4, ActivationFunction.rectified_linear_unit),
    (1, ActivationFunction.sigmoid)
])

In [272]:
%%time
titanic_model.fit(titanic_X_train, titanic_y_train)

Wall time: 1.32 s


In [273]:
titanic_predictions = titanic_model.predict(titanic_X_test)

In [274]:
titanic_predictions[titanic_predictions >= 0.5] = 1
titanic_predictions[titanic_predictions < 0.5] = 0

In [275]:
titanic_predictions = titanic_predictions.reshape((titanic_predictions.shape[0],))

In [276]:
print(f"Accuracy: {100 * sum(titanic_predictions == titanic_y_test) / len(titanic_y_test):.2f}%")

Accuracy: 82.13%
