In [1]:
import sys
sys.path.append('..')

## Data Preparing

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
path_to_file = '../datasets/classification/occupancy_detection_preprocessed.csv'
classification_df = pd.read_csv(path_to_file, index_col=0)

classification_df = classification_df.drop(['date'], axis=1)

X = classification_df.iloc[:, :-1].values
y = classification_df.iloc[:, 5].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, 
                                                    stratify=y)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [4]:
y_train, y_test = np.array(y_train), np.array(y_test)

In [5]:
y_train

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [6]:
X_train

array([[-0.04666123,  0.57976092, -0.62065626,  1.59021829,  0.5595157 ],
       [ 0.93273413,  0.55829031, -0.62065626,  0.90715833,  0.93700446],
       [-1.33251257,  0.62068927, -0.62065626, -0.82153371,  0.10467882],
       ...,
       [ 0.56309136,  1.26480756,  1.74505666,  2.10602029,  1.5175618 ],
       [ 1.20285769,  1.28946522,  1.522234  ,  2.27975276,  1.84291966],
       [ 1.13177254, -0.08381511, -0.62065626, -0.33432743,  0.32989695]])

## MLP Testing

In [10]:
from my_implementations.multilayer_perceptron.mlp import MultilayerPerceptron
from my_implementations.multilayer_perceptron.activation_functions import ActivationFunction

In [15]:
model = MultilayerPerceptron(0.1, 500, 10, [
    (3, ActivationFunction.rectified_linear_unit),
    (4, ActivationFunction.rectified_linear_unit),
    (1, ActivationFunction.sigmoid)
])

In [16]:
%%time
model.fit(X_train, y_train)

Wall time: 12.9 s


In [19]:
predictions = model.predict(X_test)

In [22]:
predictions

array([[4.50742359e-04],
       [9.73271484e-01],
       [8.49693435e-04],
       ...,
       [7.84037468e-04],
       [9.93951082e-01],
       [3.79562602e-04]])

In [23]:
preds = predictions.reshape((predictions.shape[0],))

In [26]:
preds[preds >= 0.5] = 1
preds[preds < 0.5] = 0

In [31]:
print(f"Accuracy: {100 * sum(preds == y_test) / len(y_test):.2f}%")

Accuracy: 98.88%
